### ISSUE TITLE
通过插件实现屏蔽小电视及活动链接

### ISSUE THREAD

**Issue by Plasmid0** [FYPetro/totemoe#14]

**Comment by fzql** [comment]
抽小电视时发送的弹幕示例：

    Header: 00 00 00 E3 00 10 00 00 00 00 00 05 00 00 00 00

    Message excerpt: {"cmd":"DANMU_MSG","info":[[0,1,25,16777215,1514621667,1514621667,0,"54186b6b",0],"- ( ゜- ゜)つロ 乾杯~ - bilibili",[--USERID--,"--USERNAME--",0,0,0],[],[7,">50000"],[],0,0],"roomid":"--ROOMID--"}`

普通弹幕示例：

    Message excerpt: {"info":[[0,1,25,16777215,1514622165,"266269204936116",0,"4080e82e",0],"--MESSAGE--",[--USERID--,"--USERNAME--",1,0,0,10000,1],[],[16,0,6406234,">50000"],[],0,0,{"uname_color":""}],"cmd":"DANMU_MSG"}

这个规律好像有至少一年没变过了……

**Comment by fzql** [comment]
与 #32 配合一下，重新设计首选项框，每个协议分四种等级：

1. 忽略（数据库不记录、历史文件不记录、弹幕列表不记录）
2. 隐藏（数据库记录、历史文件不记录、弹幕列表不记录）
3. 灰化（弹幕列表显示为灰色文字）
4. 正常（弹幕列表显示为黑色文字）
