### ISSUE TITLE
自动保存弹幕信息到YYYY-MM-DD-HH.TXT

### ISSUE THREAD

**Issue by qiu512398604** [FYPetro/totemoe#19]

**Comment by fzql** [comment]
这个可以有。以后考虑SQL做后台存储更多的弹幕并支持复杂视图。

**Comment by fzql** [comment]
备注：

选择存储格式：TXT、CSV

**Comment by fzql** [comment]
@qiu512398604 YYYY-MM-DD.TXT接受吗？

**Comment by qiu512398604** [comment]
@FYPetro 一天的弹幕量会不会太大了Orz

**Comment by qiu512398604** [comment]
做数据库的话要不要支持历史弹幕在线查询啊←◡←数据量好像有点惊人

**Comment by Plasmid0** [comment]
历史弹幕查询的话，会不会导致当前查找速度变慢，必须历史弹幕数量真的有点大

**Comment by fzql** [comment]
@qiu512398604 骨干级主播一般一天不过十万条弹幕，我比较相信SQL数据库的力量，实在不行，置保存7天，超期自动删。

@Plasmid0 是的，我想想哈
