### ISSUE TITLE
0.2.0版本重连问题

### ISSUE THREAD

**Issue by Plasmid0** [FYPetro/totemoe#28]
已连接，断网后显示websocket已断开，待网络正常后重连房间短号 软件报错
正常连接中，重连时有发生未响应情况

**Comment by fzql** [comment]
我关联一下 #15 号问题

**Comment by fzql** [comment]
@Plasmid0 请确认此问题是否已得到解决

**Comment by fzql** [comment]
未解决，经测试此问题仍然存在。
